name: cortical_connectome_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy=1.24.3
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - networkx
  - python-igraph
  - plotly
  - umap-learn
  - bokeh
  - streamlit
  - fastapi
  - uvicorn
  - jupyterlab
  - ipykernel
  - tqdm
  - pip
  - pip:
      - torch
      - torchvision
      - captum
      - tsne
